config changed

diff --git a/chezmoi/.chezmoiscripts/run_once_before_decrypt-private-key.sh.tmpl b/chezmoi/.chezmoiscripts/run_once_before_decrypt-private-key.sh.tmpl
--- a/chezmoi/.chezmoiscripts/run_once_before_decrypt-private-key.sh.tmpl
+++ b/chezmoi/.chezmoiscripts/run_once_before_decrypt-private-key.sh.tmpl
@@ -2,6 +2,19 @@
 
 if [ ! -f "/home/{{ .chezmoi.username }}/.config/chezmoi/keyfile" ]; then
     mkdir -p "/home/{{ .chezmoi.username }}/.config/chezmoi"
-    chezmoi age decrypt --output "/home/{{ .chezmoi.username }}/.config/chezmoi/keyfile" --passphrase "{{ .chezmoi.workingTree }}/keyfile.age"
+    cmd='chezmoi age decrypt --output "/home/{{ .chezmoi.username }}/.config/chezmoi/keyfile" --passphrase "{{ .chezmoi.workingTree }}/keyfile.age"'
+    # Initialize the attempt counter
+    attempt=1
+    max_attempts=3
+
+    while ! $cmd; do
+        if [ $attempt -ge $max_attempts ]; then
+            echo "Command failed after $attempt attempts. Exiting."
+            break
+        fi
+        echo "Command failed. Retrying..."
+        attempt=$((attempt+1))
+        sleep 1  # Optional: wait 1 second before retrying
+    done
     chmod 600 "/home/{{ .chezmoi.username }}/.config/chezmoi/keyfile"
 fi
